import type { NextPage } from 'next';
import Head from 'next/head';
import { AddTaskButton } from '../compoments/AddTaskButton';
import Card from '../compoments/Card';
import { DeleteTaskButton } from '../compoments/DeleteTaskButton';
import SidebarWithHeader from '../compoments/SideBar';
import { TaskSummaryCard } from '../compoments/Task';
import { filterOfPresentation } from '../functions/filterOfPresentation';
import { useIndexPageQuery } from '../generated/graphql';
import { withClient } from '../graphql/urql';

const Index: NextPage = () => {
  const [res] = useIndexPageQuery();
  return (
    <>
      <Head>
        <title>Task app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Stack align="center"> */}
      <SidebarWithHeader>
        <Card>
          <AddTaskButton />
          {filterOfPresentation(res.data?.tasks ?? []).map((task) => (
            <TaskSummaryCard key={task.id} task={task!}>
              <DeleteTaskButton id={task.id} />
            </TaskSummaryCard>
          ))}
        </Card>
      </SidebarWithHeader>
      {/* </Stack> */}
    </>
  );
};

export default withClient()(Index);
