import type { NextPage } from 'next';
import { withUrqlClient } from 'next-urql';
import Head from 'next/head';
import Image from 'next/image';
import { gql, useQuery } from 'urql';
import styles from '../styles/Home.module.css';

const Index: NextPage = () => {
  const [res] = useQuery({
    query: gql`
      query {
        tasks {
          id
        }
      }
    `,
  });
  console.log(res);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {res.data.tasks.map((task) => (
          <div key={task.id}>{task.id}</div>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default withUrqlClient(
  () => ({
    url: 'http://localhost:3000/api/graphql',
  }),
  { ssr: true }
)(Index);
